development:
  adapter: postgresql
  encoding: unicode
  database: recruitme_development
  host: localhost
  pool: 10
  username: matt
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: recruitme_production
  host: localhost
  pool: 25
  username: postgres
  password: fEo320zZdjwn42